routes:
  test2:
    name: test2
    path: /test/second/route
    controller: Test
    action: second
  test:
    name: test
    path: /test/{first}/route/{second}
    controller: Test
    action: first
